noun1 = ("banana")
verb1 = ("blasted")
verb2 = ("flew")
adjective1 = ("turbotastic")
adjective2 = ("enexpectedly")
celebGuest = ("Mr. Rams")
person1 = ("Thomas")
funnyPhrase1 = ("WHO PEED IN THE TUBA!")
print("for it was",(celebGuest),"birthday and the entirety of SITHS decided to surprise him with the most",(adjective1),"surprise party ever! everyone was prepping the gym when",(celebGuest),(adjective2),(verb1),"through the door shouting",(funnyPhrase1),"Everyone",(adjective1),"pointed at",(person1))