food1 = ("banana")
verb1 = ("blasted")
verb2 = ("flew")
adjective1 = ("turbotastic")
adjective2 = ("enexpectedly")
adjective3 = ("hastily")
adjective4 = ("obliviously")
celebGuest = ("Mr. Rams")
teacher = ("Mr. Whalen")
person1 = ("Thomas")
funnyPhrase1 = ("WHO PEED IN THE TUBA!")
print("for it was an average day in",(teacher),"class. ")