food1 = input("Please input a food item ")
verb1 = input("Please input a verb ")
verb2 = input("Please input a verb ")
adjective1 = input("Please input an adjective ")
adjective2 = input("Please input an adjective ")
adjective3 = input("Please input an adjective ")
celebGuest = input("Please input a celebrity guest ")
teacher = input("Please input a teacher ")
person1 = input("Please input a person ")
person2 = input("Please input a person ")
funnyExclamation1 = ("Please input a funny exclamation ")
print("For it was a",(adjective1),"day in",(teacher),"class.",(person2),"was",(verb1),"a",(food1),"when",(adjective2),(celebGuest),(verb2),"into the room shouting"(funnyExclamation1),"Everyone",(adjective3),"pointed at",(person1))